### PR TITLE
Switch from `REDEEM` custom method to virtual, create-only `InvitationRedeemRequest`

### LINKED ISSUE #131: Replace custom HTTP method 'REDEEM' with something commonly compatible
### Description

I'm working on https://github.com/appuio/cloud-portal/issues/460, specifically the Accept part where the REDEEM request (see https://kb.vshn.ch/appuio-cloud/references/architecture/control-api-invitation.html) is supposed to happen.

The problem is: A custom HTTP method is prone to incompatibilities in various places.

I'm sure there are reasons for choosing a custom method like REDEEM as opposed to something like `PUT` or `POST`, but there has to be a better solution.

### Additional Context

While a custom HTTP method _may_ work fine for most browsers, things start to break when there are Proxies between the API and browser.
Starting with the Proxy that we're using while developing the Portal itself. After debugging for an hour I noticed that the Proxy automatically turned the REDEEM request to a GET request but returned a 400 Bad Request...
I could spend more time to get a proxy working with REDEEM, but that is just fighting symptoms and still not resolving the bigger problem:

Corporate Proxies for sure won't allow custom methods.

I imagine that APPUiO Cloud has some users who are using the Portal from behind a Proxy or WAF. There's a very high chance that the feature to redeem invitations will not work in those conditions.

### Logs

_No response_

### Expected Behavior

The request is using a method that is commonly allowed, e.g. `HEAD` (preferred) or `OPTIONS`, if `POST` or `PUT` are unacceptable for some reason.

Alternatively, it may be worth thinking about a small server running on Kubernetes with its own Endpoint that can accept PUT or POST on invitations without K8s RBAC inbetween, but translates the request into something Kubernetes understands, or attempts to update the invitation accordingly for the requesting user.

### Steps To Reproduce

`curl -X REDEEM "http://localhost:8001/apis/user.appuio.io/v1/invitations/...?token=...`

### Version used

v0.19.2

### Version of OpenShift

K8s v1.25

### PR DESCRIPTION
**Pull request by bastjan**
## Summary

Fixes #131.

This PR allows redeeming invitations by creating a resource:

```
apiVersion: user.appuio.io/v1
kind: InvitationRedeemRequest
metadata:
  name: 36847652-fa97-4430-8873-08630f20d3f4
token: 60b2112f-e245-4b65-bac0-38944b9dabd4
```

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [x] Update the documentation.
  https://kb.vshn.ch/appuio-cloud/references/architecture/control-api-invitation.html#_accepting_an_invitation
  https://github.com/appuio/appuio-io-docs/pull/150
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.

### CODE REVIEW

File: apiserver/user/invitation_redeem.go [hunk 1]
```diff
@@ -17,96 +18,91 @@ import (
...
-			}
-		}
+	inv := &userv1.Invitation{}
+	if err := s.client.Get(ctx, client.ObjectKey{Name: name}, inv); err != nil {
+		return nil, fmt.Errorf("failed to get invitation: %w", err)
+	}
+
+	tokenValid := inv.Status.Token != "" && inv.Status.ValidUntil.After(time.Now())
+	if inv.IsRedeemed() || !tokenValid || inv.Status.Token != token {
+		l.Info("invalid token")
```
Comment (simu) [inline apiserver/user/invitation_redeem.go:71]: Log message is somewhat misleading, even though it's technically correct.

I'd probably go for something like the following at least

```suggestion
		l.Info("invitation already redeemed or invalid token")
```

Even nicer would be that we log why the token is invalid, but that probably needs a bit of extra logic to format the various invalid states for the log message

**Review by simu — APPROVED** [review]
LGTM overall

**Review by simu — APPROVED** [review]
